-- MySQL Script generated by MySQL Workbench
-- Mon Aug  9 16:26:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bynejs3dk0uzuzbn2sur
-- -----------------------------------------------------
-- server=bynejs3dk0uzuzbn2sur-mysql.services.clever-cloud.com; 
-- user=ucv0u4lxjvhpcjog;
-- password='hQ8fhikLVvzPAU6RIkpe'; 
-- database=bynejs3dk0uzuzbn2sur"

-- -----------------------------------------------------
-- Schema bynejs3dk0uzuzbn2sur
--
-- server=bynejs3dk0uzuzbn2sur-mysql.services.clever-cloud.com; 
-- user=ucv0u4lxjvhpcjog;
-- password='hQ8fhikLVvzPAU6RIkpe'; 
-- database=bynejs3dk0uzuzbn2sur"
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bynejs3dk0uzuzbn2sur` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bynejs3dk0uzuzbn2sur` ;

-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Persona` (
  `ID_Persona` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Tipo_Documento` VARCHAR(45) NULL,
  `Numero_ID` VARCHAR(45) NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Persona`),
  UNIQUE INDEX `ID_Persona_UNIQUE` (`ID_Persona` ASC) VISIBLE,
  UNIQUE INDEX `Numero_ID_UNIQUE` (`Numero_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Usuario` (
  `ID_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Clave` VARCHAR(45) NULL,
  `Persona_ID_Persona` INT NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  UNIQUE INDEX `ID_Usuario_UNIQUE` (`ID_Usuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Persona_idx` (`Persona_ID_Persona` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Persona`
    FOREIGN KEY (`Persona_ID_Persona`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Persona` (`ID_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Productos` (
  `ID_Producto` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Producto` VARCHAR(45) NULL,
  `Nombre_Producto` VARCHAR(45) NULL,
  `Marca_Producto` VARCHAR(45) NULL,
  `Precio_Compra` FLOAT NULL,
  PRIMARY KEY (`ID_Producto`),
  UNIQUE INDEX `ID_Producto_UNIQUE` (`ID_Producto` ASC) VISIBLE,
  UNIQUE INDEX `Codigo_Producto_UNIQUE` (`Codigo_Producto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Cliente` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Persona_ID_Persona` INT NOT NULL,
  PRIMARY KEY (`ID_Cliente`),
  UNIQUE INDEX `ID_Cliente_UNIQUE` (`ID_Cliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Persona1_idx` (`Persona_ID_Persona` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Persona_ID_Persona`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Persona` (`ID_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Ventas` (
  `ID_Venta` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Venta` DATE NULL,
  `Cliente_ID_Cliente` INT NOT NULL,
  PRIMARY KEY (`ID_Venta`),
  UNIQUE INDEX `ID_Venta_UNIQUE` (`ID_Venta` ASC) VISIBLE,
  INDEX `fk_Ventas_Cliente1_idx` (`Cliente_ID_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Cliente1`
    FOREIGN KEY (`Cliente_ID_Cliente`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Venta_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Venta_Producto` (
  `Cantidad_Productos` INT NOT NULL,
  `Precio` FLOAT NULL,
  `Productos_ID_Producto` INT NOT NULL,
  `Ventas_ID_Venta` INT NOT NULL,
  INDEX `fk_Venta_Producto_Productos1_idx` (`Productos_ID_Producto` ASC) VISIBLE,
  INDEX `fk_Venta_Producto_Ventas1_idx` (`Ventas_ID_Venta` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Producto_Productos1`
    FOREIGN KEY (`Productos_ID_Producto`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Productos` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Producto_Ventas1`
    FOREIGN KEY (`Ventas_ID_Venta`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Ventas` (`ID_Venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Empresa` (
  `ID_Empresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Empresa`),
  UNIQUE INDEX `ID_Empresa_UNIQUE` (`ID_Empresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Orden_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Orden_Pedido` (
  `ID_Orden` INT NOT NULL AUTO_INCREMENT,
  `Numero_Pedido` VARCHAR(45) NULL,
  `Fecha_Pedido` DATE NULL,
  `Empresa_ID_Empresa` INT NOT NULL,
  PRIMARY KEY (`ID_Orden`),
  UNIQUE INDEX `ID_Orden_UNIQUE` (`ID_Orden` ASC) VISIBLE,
  INDEX `fk_Orden_Pedido_Empresa1_idx` (`Empresa_ID_Empresa` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_Pedido_Empresa1`
    FOREIGN KEY (`Empresa_ID_Empresa`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Empresa` (`ID_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Productos_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Productos_Pedido` (
  `Cantidad` INT NOT NULL AUTO_INCREMENT,
  `Precio_Compra` FLOAT NULL,
  `Productos_ID_Producto` INT NOT NULL,
  `Orden_Pedido_ID_Orden` INT NOT NULL,
  PRIMARY KEY (`Cantidad`),
  UNIQUE INDEX `Cantidad_UNIQUE` (`Cantidad` ASC) VISIBLE,
  INDEX `fk_Productos_Pedido_Productos1_idx` (`Productos_ID_Producto` ASC) VISIBLE,
  INDEX `fk_Productos_Pedido_Orden_Pedido1_idx` (`Orden_Pedido_ID_Orden` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Pedido_Productos1`
    FOREIGN KEY (`Productos_ID_Producto`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Productos` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Pedido_Orden_Pedido1`
    FOREIGN KEY (`Orden_Pedido_ID_Orden`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Orden_Pedido` (`ID_Orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Producto_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Producto_Empresa` (
  `Productos_ID_Producto` INT NOT NULL,
  `Empresa_ID_Empresa` INT NOT NULL,
  INDEX `fk_Producto_Empresa_Productos1_idx` (`Productos_ID_Producto` ASC) VISIBLE,
  INDEX `fk_Producto_Empresa_Empresa1_idx` (`Empresa_ID_Empresa` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Empresa_Productos1`
    FOREIGN KEY (`Productos_ID_Producto`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Productos` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Empresa_Empresa1`
    FOREIGN KEY (`Empresa_ID_Empresa`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Empresa` (`ID_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Tipo_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Tipo_Pago` (
  `ID_Tipo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Tipo`),
  UNIQUE INDEX `ID_Tipo_UNIQUE` (`ID_Tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Egresos` (
  `ID_Egreso` INT NOT NULL AUTO_INCREMENT,
  `Factura_Servicio` VARCHAR(45) NULL,
  `Fecha_Pago` DATE NULL,
  `Concepto_Pago` VARCHAR(45) NULL,
  `Valor_Pago` FLOAT NULL,
  `Tipo_Pago_ID_Tipo` INT NOT NULL,
  PRIMARY KEY (`ID_Egreso`),
  UNIQUE INDEX `ID_Egreso_UNIQUE` (`ID_Egreso` ASC) VISIBLE,
  UNIQUE INDEX `Factura_Servicio_UNIQUE` (`Factura_Servicio` ASC) VISIBLE,
  INDEX `fk_Egresos_Tipo_Pago1_idx` (`Tipo_Pago_ID_Tipo` ASC) VISIBLE,
  CONSTRAINT `fk_Egresos_Tipo_Pago1`
    FOREIGN KEY (`Tipo_Pago_ID_Tipo`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Tipo_Pago` (`ID_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Entidad_Prestadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Entidad_Prestadora` (
  `ID_Entidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Entidad` VARCHAR(45) NULL,
  `Egresos_ID_Egreso` INT NOT NULL,
  PRIMARY KEY (`ID_Entidad`),
  UNIQUE INDEX `ID_Entidad_UNIQUE` (`ID_Entidad` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_Entidad_UNIQUE` (`Nombre_Entidad` ASC) VISIBLE,
  INDEX `fk_Entidad_Prestadora_Egresos1_idx` (`Egresos_ID_Egreso` ASC) VISIBLE,
  CONSTRAINT `fk_Entidad_Prestadora_Egresos1`
    FOREIGN KEY (`Egresos_ID_Egreso`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Egresos` (`ID_Egreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bynejs3dk0uzuzbn2sur`.`Producto_Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bynejs3dk0uzuzbn2sur`.`Producto_Inventario` (
  `ID_Prod_Inventario` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NULL,
  `Porcentaje_Utilidad` DOUBLE NULL,
  `Utilidad` FLOAT NULL,
  `Precio_Venta` FLOAT NULL,
  `Productos_ID_Producto` INT NOT NULL,
  PRIMARY KEY (`ID_Prod_Inventario`),
  UNIQUE INDEX `ID_Inventario_UNIQUE` (`ID_Prod_Inventario` ASC),
  INDEX `fk_Inventario_Productos1_idx` (`Productos_ID_Producto` ASC),
  CONSTRAINT `fk_Inventario_Productos1`
    FOREIGN KEY (`Productos_ID_Producto`)
    REFERENCES `bynejs3dk0uzuzbn2sur`.`Productos` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
